### ISSUE TITLE
[Request] Integrate whatlastgenre functionality in a beets plugin

### ISSUE THREAD

**Issue by twe4km** [YetAnotherNerd/whatlastgenre#3]
I feel like this piece of software could benefit greatly from being combined with the amazing beets, which does media library management through cli. I don't know how feasible this would be but the software is very well documented here http://beets.readthedocs.org/en/latest/

**Comment by YetAnotherNerd** [comment]
making wlg usable in plugins is on my long term todo list. there are some other tagging tools that support plugins as well, like puddletag and picard. however, at the moment there might be some user input required (interactive mode) which can be problematic in plugins. i might drop mbid tagging support first (since tools like beets and picard do this anyway) and maybe also drop releasetype tagging and focus on core functionality (genre tagging) to have no more runtime user input required at all. the code might need some other rewrites/redesign to make it usable in plugins in a more convenient way. i skipped creating plugins so far to have more freedom in terms of code redesign without having to maintain compatibility for multiple plugins.

**Comment by QuantumQweef** [comment]
^^this would be severely ravishing :]

**Comment by YetAnotherNerd** [comment]
pushed a first try of a beets plugin, see 000309fcef58fd6a660e35f6f6e24fac78ed43ba
