### ISSUE TITLE
using a custom tagsfile (data/tags.txt)

### ISSUE THREAD

**Issue by rhlahuja** [YetAnotherNerd/whatlastgenre#6]
I'd like to start off by thanking you for this awesome project. This and beets are exactly what I needed as a music enthusiast and I'm learning a lot from reading your code as well. Now to my issue...

It seems that wlg isn't refreshing my changes to tags.txt when comparing against the whitelist. I noticed the tagsfile gets initiated via the config parser unlike the whitelist which checks for a config entry first. I tried modifying the code to read the tagsfile with that join/decode statement like the whitelist but to no avail. For some reason or another, my changes to tags.txt aren't being picked up and I keep getting the "alias not whitelisted (44): ..." error. Any help or suggestions with troubleshooting would be much appreciated. Thanks!

**Comment by YetAnotherNerd** [comment]
although using a custom whitelist may make use of a custom tags.txt desirable, using one is not really supported by the code yet. we should think about how to implement the use of custom tags.txt files.
possible ideas:
* 2nd config option `tagsfile` (like `whitelist`)
* one config option `datapath` to set the path of a directory containing both files
* instead of two files, one could also just use one file, either a 'merged file' (containing data from both files) or a 'diff file' (containing changes to both shipped files)
* maybe additional: discover those files in the ~/.whatlastgenre and use them if they exist
* also possible: cmdline args to set custom paths
* in all cases: fallback to shipped files

if you make changes to the shipped tags.txt, make sure to modify the file that actually gets read. if you installed wlg, it is the copied file (in pythonpath), not the one from the git (or reinstall after changing it)

or, if you just want to change the code to use a custom file for now, try this:
```diff
diff --git a/wlg/whatlastgenre.py b/wlg/whatlastgenre.py
index f486b2e..c0b3d59 100644
--- a/wlg/whatlastgenre.py
+++ b/wlg/whatlastgenre.py
@@ -98,8 +98,8 @@ class WhatLastGenre(object):
     def read_tagsfile(self):
         '''Read tagsfile and return a dict of prepared data.'''
         tagsfile = ConfigParser.SafeConfigParser(allow_no_value=True)
-        tfstr = pkgutil.get_data('wlg', 'data/tags.txt')
-        tagsfile.readfp(StringIO.StringIO(tfstr))
+        path = os.path.expanduser('~/.whatlastgenre/tags.txt')
+        tagsfile.read(path)
         for sec in ['upper', 'alias', 'regex']:
             if not tagsfile.has_section(sec):
                 self.log.critical('Got no [%s] from tags.txt file.', sec)
```

**Comment by rhlahuja** [comment]
I was indeed modifying the git tags.txt under the impression that it's the one that gets read. When you refer to the copied file in pythonpath, do you mean the $PYTHONPATH env variable invoked with sys.path? I've looked in there (usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/) and found no tags.txt but suspect I'm searching in the wrong place. Thanks once again for your help.

**Comment by YetAnotherNerd** [comment]
mh, for me it is in an egg file `site-packages/whatlastgenre-0.1.27-py2.7.egg`. not sure if it is wise to edit it inside there. maybe try `pip install -e .` or `python setup.py develop`

**Comment by rhlahuja** [comment]
Yea I see site-packages/whatlastgenre-0.1.27-py2.7.egg but not quite sure I
understand what to do with it. Will this allow me to make changes to the
shipped tags.txt?

**Comment by rhlahuja** [comment]
Nvm, I realized I can simply unzip then modify and build a new egg!

**Comment by rhlahuja** [comment]
I'll still be trying your suggested code changes though and will report back.

**Comment by rhlahuja** [comment]
Figured reinstalling after changing is easier for now but will try your suggested code changes later and report back.
